version: '3.5'
services:
  heisl-frontend:
    container_name: heisl-frontend-lint
    build:
      context: .
      target: build
    entrypoint:
      - /bin/sh
      - -c
    command:
      - npm run lint
