version: '3.5'
services:
  heisl-frontend:
    container_name: heisl-frontend
    image: heisl-frontend
    build:
      context: .
      target: build
    ports:
      - "8100:8100"
    volumes:
      - ${PWD}/frontend/:/app/
      - /app/node_modules/
    networks:
      - heisln-net
    entrypoint:
      - /bin/sh
      - -c
    command:
      - ionic serve --host 0.0.0.0 -b

networks:
  heisln-net:
    external: true
