/**
 * Heisln.Car.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarInfo } from './car-info';


export interface Booking { 
    id?: string | null;
    carId?: string | null;
    car?: CarInfo;
    userId?: string;
    startDate?: string;
    endDate?: string;
}

