/**
 * Heisln.Car.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Currency = 'USD' | 'JPY' | 'BGN' | 'CZK' | 'DKK' | 'GBP' | 'HUF' | 'PLN' | 'RON' | 'SEK' | 'CHF' | 'ISK' | 'NOK' | 'HRK' | 'RUB' | 'TRY' | 'AUD' | 'BRL' | 'CAD' | 'CNY' | 'HKD' | 'CIDR' | 'ILS' | 'INR' | 'KRW' | 'MXN' | 'MYR' | 'NZD' | 'PHP' | 'SGD' | 'THB' | 'ZAR';

export const Currency = {
    Usd: 'USD' as Currency,
    Jpy: 'JPY' as Currency,
    Bgn: 'BGN' as Currency,
    Czk: 'CZK' as Currency,
    Dkk: 'DKK' as Currency,
    Gbp: 'GBP' as Currency,
    Huf: 'HUF' as Currency,
    Pln: 'PLN' as Currency,
    Ron: 'RON' as Currency,
    Sek: 'SEK' as Currency,
    Chf: 'CHF' as Currency,
    Isk: 'ISK' as Currency,
    Nok: 'NOK' as Currency,
    Hrk: 'HRK' as Currency,
    Rub: 'RUB' as Currency,
    Try: 'TRY' as Currency,
    Aud: 'AUD' as Currency,
    Brl: 'BRL' as Currency,
    Cad: 'CAD' as Currency,
    Cny: 'CNY' as Currency,
    Hkd: 'HKD' as Currency,
    Cidr: 'CIDR' as Currency,
    Ils: 'ILS' as Currency,
    Inr: 'INR' as Currency,
    Krw: 'KRW' as Currency,
    Mxn: 'MXN' as Currency,
    Myr: 'MYR' as Currency,
    Nzd: 'NZD' as Currency,
    Php: 'PHP' as Currency,
    Sgd: 'SGD' as Currency,
    Thb: 'THB' as Currency,
    Zar: 'ZAR' as Currency
};

